// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ErnSuVOh8axuHaL9_35PCHje67Ljk6U',
    appId: '1:590668562819:web:2d51b0650c15e71620f6b6',
    messagingSenderId: '590668562819',
    projectId: 'datingapp-772a6',
    authDomain: 'datingapp-772a6.firebaseapp.com',
    storageBucket: 'datingapp-772a6.firebasestorage.app',
    measurementId: 'G-P19XBTDP21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJW_h9QRCyYE_f8C2EIAcxaTW_oANS3eI',
    appId: '1:590668562819:android:61690d006594cb8920f6b6',
    messagingSenderId: '590668562819',
    projectId: 'datingapp-772a6',
    storageBucket: 'datingapp-772a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2UeOwa2yz9fi4ZnJf32ufPxLZCS11kSo',
    appId: '1:590668562819:ios:2308b2c3c9ddee6320f6b6',
    messagingSenderId: '590668562819',
    projectId: 'datingapp-772a6',
    storageBucket: 'datingapp-772a6.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2UeOwa2yz9fi4ZnJf32ufPxLZCS11kSo',
    appId: '1:590668562819:ios:2308b2c3c9ddee6320f6b6',
    messagingSenderId: '590668562819',
    projectId: 'datingapp-772a6',
    storageBucket: 'datingapp-772a6.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ErnSuVOh8axuHaL9_35PCHje67Ljk6U',
    appId: '1:590668562819:web:51c6508cbbcc039220f6b6',
    messagingSenderId: '590668562819',
    projectId: 'datingapp-772a6',
    authDomain: 'datingapp-772a6.firebaseapp.com',
    storageBucket: 'datingapp-772a6.firebasestorage.app',
    measurementId: 'G-KWLQEVQYKF',
  );
}
