import 'onboarding_data.dart';

/// لیست زبان‌ها برای بخش «زبان‌هایی که بلدم» تو صفحه‌ی پروفایل. لیست تیندر
/// خیلی بلندتر از اینه (نزدیک ۱۵۰ زبان)؛ اینجا رایج‌ترین‌ها + چندتای دیگه
/// به ترتیب حروف الفبای فارسی برچسب‌هاشون اومده. هر وقت خواستی می‌تونی
/// همین‌جا OptionItem جدید اضافه کنی، نیازی به تغییر جای دیگه نیست.
const List<OptionItem> kLanguageOptions = [
  OptionItem('afrikaans', 'آفریکانس'),
  OptionItem('albanian', 'آلبانیایی'),
  OptionItem('amharic', 'امهری'),
  OptionItem('arabic', 'عربی'),
  OptionItem('armenian', 'ارمنی'),
  OptionItem('asl', 'زبان اشاره‌ی آمریکایی'),
  OptionItem('azerbaijani', 'آذربایجانی'),
  OptionItem('bengali', 'بنگالی'),
  OptionItem('bosnian', 'بوسنیایی'),
  OptionItem('bulgarian', 'بلغاری'),
  OptionItem('burmese', 'برمه‌ای'),
  OptionItem('cantonese', 'کانتونی'),
  OptionItem('catalan', 'کاتالان'),
  OptionItem('croatian', 'کرواتی'),
  OptionItem('czech', 'چکی'),
  OptionItem('danish', 'دانمارکی'),
  OptionItem('dutch', 'هلندی'),
  OptionItem('english', 'انگلیسی'),
  OptionItem('estonian', 'استونیایی'),
  OptionItem('filipino', 'فیلیپینی'),
  OptionItem('finnish', 'فنلاندی'),
  OptionItem('french', 'فرانسوی'),
  OptionItem('georgian', 'گرجی'),
  OptionItem('german', 'آلمانی'),
  OptionItem('greek', 'یونانی'),
  OptionItem('gujarati', 'گجراتی'),
  OptionItem('hausa', 'هوسا'),
  OptionItem('hebrew', 'عبری'),
  OptionItem('hindi', 'هندی'),
  OptionItem('hungarian', 'مجاری'),
  OptionItem('icelandic', 'ایسلندی'),
  OptionItem('indonesian', 'اندونزیایی'),
  OptionItem('italian', 'ایتالیایی'),
  OptionItem('japanese', 'ژاپنی'),
  OptionItem('javanese', 'جاوه‌ای'),
  OptionItem('kannada', 'کانادایی (زبان هند)'),
  OptionItem('kazakh', 'قزاقی'),
  OptionItem('khmer', 'خمری'),
  OptionItem('korean', 'کره‌ای'),
  OptionItem('kurdish', 'کردی'),
  OptionItem('lao', 'لائوسی'),
  OptionItem('latin', 'لاتین'),
  OptionItem('latvian', 'لتونیایی'),
  OptionItem('lithuanian', 'لیتوانیایی'),
  OptionItem('malay', 'مالایی'),
  OptionItem('malayalam', 'مالایالام'),
  OptionItem('mandarin', 'ماندارین'),
  OptionItem('marathi', 'مراتی'),
  OptionItem('mongolian', 'مغولی'),
  OptionItem('nepali', 'نپالی'),
  OptionItem('norwegian', 'نروژی'),
  OptionItem('pashto', 'پشتو'),
  OptionItem('persian', 'فارسی'),
  OptionItem('polish', 'لهستانی'),
  OptionItem('portuguese', 'پرتغالی'),
  OptionItem('punjabi', 'پنجابی'),
  OptionItem('romanian', 'رومانیایی'),
  OptionItem('russian', 'روسی'),
  OptionItem('serbian', 'صربی'),
  OptionItem('sinhala', 'سینهالی'),
  OptionItem('slovak', 'اسلواکی'),
  OptionItem('slovenian', 'اسلوونیایی'),
  OptionItem('somali', 'سومالی'),
  OptionItem('spanish', 'اسپانیایی'),
  OptionItem('swahili', 'سواحیلی'),
  OptionItem('swedish', 'سوئدی'),
  OptionItem('tagalog', 'تاگالوگ'),
  OptionItem('tamil', 'تامیل'),
  OptionItem('telugu', 'تلوگو'),
  OptionItem('thai', 'تایلندی'),
  OptionItem('turkish', 'ترکی استانبولی'),
  OptionItem('ukrainian', 'اوکراینی'),
  OptionItem('urdu', 'اردو'),
  OptionItem('uzbek', 'ازبکی'),
  OptionItem('vietnamese', 'ویتنامی'),
  OptionItem('zulu', 'زولو'),
];
